### ISSUE TITLE
which  version support .net framework 4.0 

### ISSUE THREAD

**Issue by John0King** [dotliquid/dotliquid#446]
I have an very old project that using still use  `var tmpl = "<html>" + var1 + "</html>"`  ,  and I want to use this dotliquid to render the template ,  but now there only support  .net standard 2.0  above,  

so I'm asking  what's the  latest version of dotliquid   support .net framework 4.0 (older version on nuget do not show what TFM it  support  ?

**Comment by microalps** [comment]
All v2.x branches are built for .NET 4.5 and higher. It seems, based on the release logs, that v1.8 had a 4.5 and 3.5 build. NuGet package for that version has a build for 3.5, 4.0 and 4.5. The next version, v2.0.24, has 4.5 only.

As MS has ended support for .NET 4.0 runtime, any OS since XP has the opportunity to install v4.5+. We would strongly recommend you upgrade your project and recompile.
