### ISSUE TITLE
split filter not working

### ISSUE THREAD

**Issue by rracasanu** [dotliquid/dotliquid#49]
I have tried to use the split filter as documented here: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers but it does not seem to work.

Looking into the source code, it does not seem to be implemented.

**Comment by Ankasalahari** [comment]
Here is the one of the example 
"franchises":[
{% assign beatles = "12,34,56" | split: "," %}

{% for member in beatles %}
{
  {{ member }}
},
{% endfor %}
]
 here the split is not working

**Comment by Attosius** [comment]
If someone have this bug, try to use CamelCase with operators
`
{% assign testArray = "first/second/third/fourth" | Split: '/' %}

First element: {{testArray | First}}
Last element: {{testArray | Last}}
Size: {{testArray | Size}}
`
It helped me

**Comment by thinkOfaNumber** [comment]
It's 2023, is this an undocumented feature? 

    {%- assign emailLowerSplit = "me@here.com" | split: '@' -%}
    {%- assign emailUpperSplit = "me@here.com" | Split: '@' -%}
    {% for part in emailLowerSplit -%}
      {{ part }}
    {% endfor %}
    {% for part in emailUpperSplit -%}
      {{ part }}
    {% endfor %}

produces

    m
    e
    @
    h
    e
    r
    e
    .
    c
    o
    m
  
    me
    here.com

**Comment by microalps** [comment]
@thinkOfaNumber this is expected behavior

1. split and Split are not synonyms. Depending on the selected naming convention, one or the other will work. In your case, the `CSharpNamingConvention` seems in use.
2. Using an unknown filter is ignored and value remains unchanged. SO: split results in string object while Split has a string array.
3. string are char array in c# so for loops on the former iterate character by character while the string array works as you want.
