### ISSUE TITLE
Negative index on array does not count from the end of the array

### ISSUE THREAD

**Issue by AnEvilPenguin** [dotliquid/dotliquid#497]
### Dotliquid version
2.2.656

### Expected behavior

> A negative index will count from the end of the array.

https://shopify.github.io/liquid/basics/types/#array

```


Tobi
Laura
Adam

```

### Actual behavior

```


Tobi
Laura
Liquid error: Index was outside the bounds of the array.

```

### Steps to reproduce the Problem (you can add files)

```

{% assign users = "Tobi,Laura,Tetsuro,Adam" | split: ',' %}

{{users[0]}}
{{users[1]}}
{{users[-1]}}

```

### Further detail

When more directly reproducing the documentation you may also encounter:

> Liquid error: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

```

var json = @"{
	""site"": {
		""users"": [
			""Tobi"",
			""Laura"",
			""Tetsuro"",
			""Adam""
		]
	}
}";

var template = Template.Parse(@"
{{ site.users[0] }}
{{ site.users[1] }}
{{ site.users[-1] }}");
		
var parsedJson = JsonConvert.DeserializeObject<ExpandoObject>(json, new ExpandoObjectConverter());
var hashFromDictionary = Hash.FromDictionary(parsedJson);
Console.Write(template.Render(hashFromDictionary));

```

**Comment by microalps** [comment]
Did some more testing and it turns out that Ruby also allows you to specify an index out of bounds (and returns null). This is even if you specify strict variable checking in liquid, because again it just leaves it up to ruby. I don't believe this should be the case with the DotLiquid, but I can see both sides of the coin. I've committed my change for strictly this use case.
