### ISSUE TITLE
Website http://dotliquidmarkup.org/ doesn't load

### ISSUE THREAD

**Issue by Jojoshua** [dotliquid/dotliquid#518]
This URL is linked on the Github repo and many other places on the web but it never loads for me, does anyone else have the same problem?

**Comment by microalps** [comment]
@tgjones this is on AppHarbor site
> [AppHarbor is Shutting Down](https://blog.appharbor.com/2022/11/09/shutting-down-appharbor)
Today I have sad news to share with you. Early next month, AppHarbor will unfortunately be shutting down after almost 12 years in business. It's been quite a ride and it truly has been a pleasure and privilege to serve our customers and the .NET community throughout all these years. Read on for details of what this means for AppHarbor customers.

**Comment by microalps** [comment]
Since we haven't heard from Tim in ~2 years, I've stood up www.dotliquid.org to replace the old domain. It is not currently part of CI builds, is hosted on my own infrastructure, and I hope that it doesn't get abused and can remain there. If anyone wants to offer to setup CI builds and hosting, we should chat.
