### ISSUE TITLE
Issue in Extends.cs can cause memory issues.

### ISSUE THREAD

**Issue by neilkinnish** [dotliquid/dotliquid#67]
b.AddRange should be moved - see below

```
if (block != null)
{
    Block found = b.Find(bl => bl.BlockName == block.BlockName);

    if (found != null)
        found = block;
    else
        b.Add(block);
}

b.AddRange(FindBlocks(n, b)); // this line should be moved up into the if statement
```

**Comment by jonorossi** [comment]
I know this is a very old issue, but I thought I'd add more info in case someone else runs into it in the future (or is still using 1.7.0) to save them chasing it down. Nancy 1.x still uses DotLiquid 1.7.0 which has this problem.

After adding a handful of variable outputs into the parent/layout template I started getting:
> Liquid error: Exception of type 'System.OutOfMemoryException' was thrown.

I noticed that each extra variable I added to the template the slower the render got until it OOM.

Pulling the source code for 1.7.0 (3 Aug 2012) I found the `Extends.FindBlocks` method is definitely broken, the `blocks` parameter isn't even used by the method:
https://github.com/dotliquid/dotliquid/blob/9331a9aabb4af11a2f2962e237f6dc970dde28c5/src/DotLiquid/Tags/Extends.cs#L157-L190

In `FindBlocks` in 1.7.0 with 4 blocks in my parent template I ended up getting 202,375,168 blocks in the `b` list before it OOM, without the extra variables I added to the template it had a high of 197,634 blocks, so it worked but definitely a performance hit. With the `FindBlocks` code from master patched into 1.7.0 it now gets a high of 4 blocks because the `b` variable is gone.

The fix was done in 65ab99c6f080d4d3f8b2a9a5b2c51d639ddc7cbe (part of #61) authored 15 May 2012 and committed 13 Dec 2012, so missed 1.7.0. I haven't yet confirmed since the Git repo is missing tags but it should be fixed in 1.8.0+.
